### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by captainnemo2005** [matsim-org/matsim-episim#28]
Hi team, 

very interested work but while I installed the package in my computer "mvn package" to get the stand alone file.
However, the packge failed. 
[ERROR] with 6 test cases fail:
One example: 
 +  RunEpisimIntegrationTest.tearDown:56->assertSimulationOutput:68 
File:
File:
  </Users/cptnemo2005/Downloads/matsim-episim-master/test/output/org/matsim/run/RunEpisimIntegrationTest/testPlausibleShutdown[it100]/infections.txt>
and file:
  </Users/cptnemo2005/Downloads/matsim-episim-master/test/input/org/matsim/run/RunEpisimIntegrationTest/testPlausibleShutdown[it100]/infections.txt>
do not have same content:

**Comment by rakow** [comment]
Very strange, since the travis build is not failing. I will check this. Meanwhile you can build with
`mvn package -DskipTests`

**Comment by rakow** [comment]
It should be working now. Thanks for bringing this to our attention.
