### ISSUE TITLE
Event file won't run if all transit vehicles are prefixed with "tr_"

### ISSUE THREAD

**Issue by idshklein** [matsim-org/matsim-episim#43]
Hello,
I have recently tried to run episim on the output of a different model than the open berlin scenario. In this model, transit vehicles are not prefixed with "tr_" as in the open Berlin scenario, and therefore the model get stuck once it identifies an infection container is in PT.
I browsed through the code and saw that the "tr" prefix is embedded in the code.
Is there a way using episim and matsim to prevent this? For know, I'm using an R script to bypass this, but it is not preferable.
Best
Ido Klein

**Comment by rakow** [comment]
It is possible to change the prefix via the `InfectionParams` config, but I assume there is no common prefix in your case.
Looking through It again I think it should not be a big problem to make it run without  a prefix, but it certainly would require some changes.

If you could send me a small sample event file similar to the one for [Berlin](https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-1pct/output-berlin-v5.4-1pct/berlin-v5.4-1pct.output_events_for_episim.xml.gz"´) (1% should be enough), I will be able to take a closer look at this issue.

**Comment by idshklein** [comment]
[jlm.output_events-0.1.xml.gz](https://github.com/matsim-org/matsim-episim/files/5090812/jlm.output_events-0.1.xml.gz)
[TAMA.output_events-0.1.xml.gz](https://github.com/matsim-org/matsim-episim/files/5090817/TAMA.output_events-0.1.xml.gz)
these are 10% of Jerusalem and Tel aviv. thank you

**Comment by rakow** [comment]
Yes, that just the prefix that was used in the scenarios we are using so that's why we kept using it.
