### ISSUE TITLE
Definition of containerId for facilities and vehicles

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-episim#46]
I am trying to find the formal definition of the containerId for both facilities and transit vehicles.

I have the following infectionEvent example facility:

`home_5221371369291700047_5221371409207944593`

In this case I believe the containerId is concatenation of the infectionType and the link id on the network. I can therefore plot the event by looking up the spatial coordinates of the link id.

For a `pt` example:

`veh_2750_rail `

In this case I believe the containerId is a concatenation of vehicle + service id from schedule + mode. I can plot this spatially using the service id and the timestamp. 

Would you be able to confirm or point me to the direct reference in the code?

**Comment by rakow** [comment]
You can see how the id of facilities is constructed here:

https://github.com/matsim-org/matsim-episim/blob/b1bc2539d815ea6ec4d8680082065817e60ea937/src/main/java/org/matsim/episim/InfectionEventHandler.java#L610

I assume there are no facility ids present in your data. In this case you are correct, as it will be a concatenation of the first part of the activityType and linkId. (See linked code for the exact way it works)

In the case of vehicles, it is simply the same as the vehicle id.

**Comment by gac55** [comment]
Thank you @rakow
