### ISSUE TITLE
Toggle contact tracing off

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-episim#47]
I can see from the generated configuration post episim that I am using contact tracing:

```
<module name="episimTracing" >
		<!-- Possible values: PER_PERSON, PER_CONTACT_PERSON -->
		<param name="capacityType" value="PER_PERSON" />
		<param name="equipmentRate" value="1.0" />
		<param name="locationThreshold" value="4" />
		<param name="minDuration" value="0.0" />
		<param name="putTraceablePersonsInQuarantineAfterDay" value="2147483647" />
		<param name="quarantineHousehold" value="false" />
		<!-- Possible values: INDIVIDUAL_ONLY, LOCATION, LOCATION_WITH_TESTING -->
		<param name="strategy" value="INDIVIDUAL_ONLY" />
		<param name="traceSusceptible" value="true" />
		<param name="tracingCapacity" value="" />
		<param name="tracingDaysDistance" value="4" />
		<param name="tracingDelay" value="0" />
		<param name="tracingProbability" value="" />
	</module>
```

How do I turn contact tracing off? I am carrying out a baseline scenario, pre any form of behaviour change or intervention. 

I am using a module to define my scenario, very similar to https://github.com/matsim-org/matsim-episim/blob/master/src/main/java/org/matsim/run/modules/OpenBerlinScenario.java

Thank you

**Comment by rakow** [comment]
Contact tracing is enabled for a specific day with:
		<param name="putTraceablePersonsInQuarantineAfterDay" value="2147483647" />

The default is max integer and also what is set in your config. Consequently, the contact tracing is already off in your run.

**Comment by gac55** [comment]
I see, so 

```
		<param name="putTraceablePersonsInQuarantineAfterDay" value="2147483647" />
```

means that contact tracing kicks in on day `2147483647` ?

**Comment by rakow** [comment]
Yes, exactly! This is what we also use. There is no dedicated "off" switch unfortunately, but it achieves the same.

**Comment by gac55** [comment]
Excellent.

Thanks again for the swift response.
