### ISSUE TITLE
Support for parameter callibration

### ISSUE THREAD

**Issue by SohYeeLee** [matsim-org/matsim-episim#50]
Hi,

May you provide some guidelines to calibrate the parameter? What files are needed, and how do they look like?
Posted here as requested.

Thanks.

**Comment by rakow** [comment]
Hi,

Are you refering to input or output files?

In order to run a scenario you need a MATSim events file, which you can obtain by running any MATSim scenario.
How you calibrate the calibration parameter "theta" (set in the Episim Config) is up to you.

Episim will write an "infections.txt" to the output directory.
This file will contain daily number of people infected, showing symptoms, in critical state, etc.

You can use this simulation output and compare it will real-world infection data from the same region if you have that available.
Alternatively you can also calibrate in such a way that the infections number double every x days, so you obtain a similar exponential growth as in reality.

**Comment by SohYeeLee** [comment]
Hi rakow,

Thank you very much for details. I've been using this model for few weeks now, so I'm familiar with how it runs. Thanks for the great model!

Now, I'm looking at "python/analysis/calibrate.py". There's a method called "read_data", which takes 3 csv files. 

![read_data](https://user-images.githubusercontent.com/51136409/99537020-6aa0c680-29ab-11eb-9715-c44831a8f733.PNG)
May I know how they should look like? Is it something already available in the public-svn as shown in attachment?

![fall-zahlen](https://user-images.githubusercontent.com/51136409/99537031-6e344d80-29ab-11eb-96d4-112a79113b6d.PNG)

Thanks again.
Lee

**Comment by rakow** [comment]
Sorry, I didn't know you are referring to this file. We use it internally, so the workflow is unfortunately not documented.

But you can try to run it like this:

    python calibrate.py 5 --runs 3 --scenario <YOUR SCENARIO>

The files you need are indeed on the public svn.

f -> simulation output, i.e. infections.txt of a run

hospital -> https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/episim/original-data/Fallzahlen/Berlin/berlin-hospital.csv

rki -> https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/episim/original-data/Fallzahlen/RKI/berlin-cases.csv

If you want to use your own you might simply replace the default values in the python script.

**Comment by SohYeeLee** [comment]
Thank you, it's really helpful!

**Comment by SohYeeLee** [comment]
Hi, just want to thank the team again for making the Snz data public. 
When I'm trying to run the Snz production scenario, I get an error that a file called "BerlinSnzData_daily_until20201107.csv" is not found. 

May I know where can I get an approximate value for this (if this is not publicly available?), and what's the format for this .csv?

Thank you again.

**Comment by rakow** [comment]
A suitable file should be in the SVN now. You might have to adjust the filename, though.

**Comment by SohYeeLee** [comment]
Thanks for the very quick response. I can download it from the SVN now. 

Additional question:
What network file is suitable for Snz data? When I loaded the network file from [berlin svn](https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-1pct/output-berlin-v5.4-1pct/,) to Via program, the "link" between facilities cannot be found (although it's not needed to in Episim model).

**Comment by rakow** [comment]
The network for OpenBerlin can not be used with the snz model. 
The snz network is not part of the open data at this point and is as you said not needed to run the scenario.

**Comment by SohYeeLee** [comment]
Thank you so much again!
