### ISSUE TITLE
Seeding at initialisation - how to ensure random 

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-episim#52]
We have ran multiple simulations with the following set:

`config.global().setRandomSeed(10);`

We understood this to mean 10 random agents selected as infected. However, we see consistent outputs across the episim results suggesting that the same seed is being used. 

In the outputted config file we see:
```
<param name="snapshotSeed" value="restore" />
```

This suggests that some state is being captured and re-used for the 10 initial agents. Can you advise how we can ensure a random seed is used each time?

Thank you

**Comment by rakow** [comment]
`config.global().setRandomSeed` is a global MATSim option and sets the state of the random number generator.
If you want to have different results you have to run with different random seeds.

Infecting 10 agents randomly is episim specific and can be configured as follows:

	episimConfig.setInitialInfections(10);

You can also set how many agents should be infected per day (until the number of initial infections is reached):

	episimConfig.setInfections_pers_per_day(Map.of(
		LocalDate.of(2020, Month.FEBRUARY, 1), 5
	));

This example infects 5 agents per day, beginning at 2020-02-01

**Comment by gac55** [comment]
Thanks!

Should this require me to run `mvn clean` and `mvn package` in-between invocations? I am using the `modules` functionality, similar to the OpenBerlin [example](https://github.com/matsim-org/matsim-episim/blob/master/src/main/java/org/matsim/run/modules/OpenBerlinScenario.java).

**Comment by rakow** [comment]
If you run from command line using `java -jar ...` with the produced jar file you need to invoke `mvn package` to build a new jar each time you change anything in the scenario.

If you run from an IDE you usually don't need to run the maven build.

**Comment by gac55** [comment]
Thanks for the help. 

I've tried invoking the command with and without rebuilding the jar each time. I still see a static seed being used.

My test is to inspect the output `infectionEvents.txt` file. I see the same infector-infected behaviour across multiple invocations. 

Perhaps I have a misconfiguration elsewhere?

```
/*-
 * #%L
 * MATSim Episim
 * %%
 * Copyright (C) 2020 matsim-org
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */
package org.matsim.run.modules;

import com.google.inject.AbstractModule;
import com.google.inject.Provides;
import com.google.inject.Singleton;
import org.matsim.core.config.Config;
import org.matsim.core.config.ConfigUtils;
import org.matsim.episim.EpisimConfigGroup;
import org.matsim.episim.policy.FixedPolicy;

public class Baseline extends AbstractModule {

	/**
	 * Activity names of the default params from {@link #addDefaultParams(EpisimConfigGroup)}.
	 */
	public static final String[] DEFAULT_ACTIVITIES = {
			"veh", "pt", "education", "escort", "home_0_8", "home_8_p", "medical", "other", "recreation", "personal", "religious", "work_9to5am", "work_9to5pm", "work_0_3", "visit", "work_9to5", "work_7_p", "work_3_7", "shop", "activity"
	};

	/**
	 * Adds default parameters that should be valid for most scenarios.
	 */
	public static void addDefaultParams(EpisimConfigGroup config) {
		config.getOrAddContainerParams("veh", "pt", "tr", "medical", "veh","empbus","pbus");
		// regular out-of-home acts:
		config.getOrAddContainerParams("work", "work_9to5am", "work_9to5pm", "work_0_3", "work_9to5", "work_7_p", "work_3_7");

	}

	@Provides
	@Singleton
	public Config config() {

		Config config = ConfigUtils.createConfig(new EpisimConfigGroup());
		EpisimConfigGroup episimConfig = ConfigUtils.addOrGetModule(config, EpisimConfigGroup.class);

		episimConfig.setFacilitiesHandling(EpisimConfigGroup.FacilitiesHandling.bln);

		episimConfig.setInputEventsFile("./epi-test/output_events-1.0.xml.gz");

		// 1perc
		episimConfig.setSampleSize(0.01);
		episimConfig.setCalibrationParameter(0.0005);

		config.global().setRandomSeed(10);
		episimConfig.setInitialInfections(10);

		episimConfig.setStartDate("2020-02-15");

		addDefaultParams(episimConfig);


		return config;
	}

}
```

**Comment by rakow** [comment]
Did you double-check you have used different values for `config.global().setRandomSeed(10)` ?
From what I can see it looks correct and it should produce different results with a different seed.

**Comment by gac55** [comment]
Thanks @rakow :) 

Sorted.
