### ISSUE TITLE
Super spreaders & reinfection rate

### ISSUE THREAD

**Issue by tuhin9443** [matsim-org/matsim-episim#54]
I have some queries related to the project and I would really appreciate if you could help me with my questions. Kindly could you tell whether episim supports super spreader scenarios and how can I get it to work. Also could you tell me in the reinfection rate in parameter calibration what does days variable indicate and how do you choose the value 20. Can you breifly explain how the reinfection rate is used for base parameter calibration ?

**Comment by rakow** [comment]
Please see here for some info on the reinfection rate: https://github.com/matsim-org/matsim-episim/issues/51

Super-spreading should happen naturally in episim, depending on the scenario. Some factors that constitute super-spreading are:

- Certain activities with high contact intensity and many participants
- Certain persons that interact with a lot of people over the course of a day
- Persons that are a lot more infectious than others

Point 1 and 2 depend mostly on your input data, i.e. daily activity trajectories.

For point 3 there is a infection model that allows to assign a different infectiousness to each individual person:

https://github.com/matsim-org/matsim-episim/blob/af8137da3d822854a709a40630c35282faa45c46/src/main/java/org/matsim/episim/model/InfectionModelWithViralLoad.java#L16

An example to initialize it is here:

https://github.com/matsim-org/matsim-episim/blob/a03f98be86b6b24972c35dd35efb1da7384e5778/src/main/java/org/matsim/run/modules/SnzBerlinSuperSpreaderScenario.java#L163-L166

**Comment by tuhin9443** [comment]
Thank you ! This was  really helpful.
