### ISSUE TITLE
Leisure Activities

### ISSUE THREAD

**Issue by tuhin9443** [matsim-org/matsim-episim#61]
Hello,

In the output of the infections data I see that the infections happening in activities like leisure, shop are very very less  compared to those happening at homes and work places. Kindly could you let me know whether this is due to the design of the events data or the episim is handling these activities in a different way.

**Comment by rakow** [comment]
To which events are you referring to? All activity are handled according to its `InfectionParams`.

**Comment by tuhin9443** [comment]
Hello,

When I am trying to run the OpenBerlinScenario with the berlin data which is provided by you I am getting a very very less amount of infections (800 infections around) in the output infections xml data for some activities like leisure inspite of running it for 200 days with initial infections 80. But infections in places like home and work are very very high in the order 80-90k. I will check the infection params

**Comment by rakow** [comment]
In the example leisure is closed completely in iteration 14. If you haven't changed the defaults this will be the reason, no infections take place during leisure anymore.
Also, please keep in mind that the scenario is just an example on how to model certain restrictions. It is not calibrated at all.

**Comment by tuhin9443** [comment]
Thank you. I will check that. I just wanted to know why the values for leiusre is so less.

**Comment by tuhin9443** [comment]
Hello ,

After commenting the restrictions and shutdown I am getting 841 infections in shops, 843 infections in leisure , 9310 infections in pt, 6898 in work for 200 days with 80 initial infections. I am running the Open berlin scenario with the data that is available for us. I was just curious whether  the low number of infections in leisure and shops seems to be ok. It just seemed too less to me but maybe the encounters or interactions of people in these activities are so less that the infection numbers are less.
