### ISSUE TITLE
groupsize, totalUsers, and maxGroupSize intepretation at output

### ISSUE THREAD

**Issue by SohYeeLee** [matsim-org/matsim-episim#62]
Hi again,

May you help to confirm the interpretation of output.

1. At infectionEvents.txt, is the `groupSize` mean that the number of persons that's currently in that container when infections happened?

2. Does the `totalUsers` in containerUsage.txt.gz match the `groupSize` in infectionEvents.txt? 

3. Is the `maxGroupSize` in containerUsage.txt.gz derived from the setSpacesPerFacility defined in Scenario?

4. How is the types in containerUsage.txt.gz calculated? The sum is not matching the `totalUsers` although after divided by _sampleSize_ (I used the 25pc snz berlin scenario):
```
id        types             totalUsers             maxGroupSize
123456 {errands=>68, business=>1}	308	40
```

Thanks a lot!

**Comment by rakow** [comment]
1. Infection events contain the group size, with current number of people in the container, as you described it.
2. No, there is no totalUsers in infection events.
3. maxGroupSize is derived purely from the events and is the maximum number of persons simultaneously in the container. spacesPerFacility is not considered in this number.
4. It seems that when calculating the types, some circular trajectories, or trajectories without a start event are not taken into account. This is some older value that may not be so accurate in a multi-day model. It is not used anywhere, so probably wasn't updated. You might want to be careful if you intend to use it for something.

**Comment by SohYeeLee** [comment]
Sorry I made a mistake in the previous writing, and has corrected it.
For question 2: Is `totalUsers` the total number of people visiting the facility in a day?

**Comment by rakow** [comment]
Yes, total `totalUsers` is supposed to be the total numbers of users. It has the same problems as `types`, though. In a multi-day model it will be over all the defined days. (But not necessarily a whole week)

**Comment by SohYeeLee** [comment]
Thanks very much!
